# Sam Tenney
# Homework 11
# Peanut.R

# Read in the data
peanut <- read.table(text = "treatment,outcome
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,FAIL OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Consumption,PASS OFC
Peanut Consumption,PASS OFC
Peanut Avoidance,PASS OFC
Peanut Avoidance,PASS OFC", header = TRUE, sep = ",")

# Look at the data
str(peanut)
head(peanut)
tail(peanut)

# Create a table of the data
peanutTab <- table(peanut$treatment, peanut$outcome)
addmargins(peanutTab)

# Calculate proportions with peanut allergy in each group
prop.table(peanutTab, margin = 1)

# Perform a chi squared test
chisq.test(peanutTab, correct=FALSE)

# Perform a Fisher's Exact Test
fisher.test(peanutTab)

# Calculate a 95% confidence interval for the diff in proportions
prop.test(peanutTab, correct = FALSE)
